version: '3'

services:
  validator:
    build: ./validator
    image: validator:0.1
    volumes:
      - ./validator/code:/appcode
      - ./conditions:/tmp/conditions
      - ./organizations:/tmp/organizations
    command: python3 run.py
